
version: '3,4'

services: 
  basketredis:
    container_name: basketredis
    ports:
      - "6379:6379"
    volumes:
      - basketredis_data:/data/db

  basket-api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStringRedis=basketredis:6379"
      - "RabbitMQSettings__HostName={hostnameRabbitMQ}"
      - "RabbitMQSettings__Username={usernameRabbitMQ}"
      - "RabbitMQSettings__Password={passwordRabbitMQ}"
    depends_on:
      - basketredis
    ports:
      - "8001:80"
