version: '3.4'

services:
  catalogdb02:
    image: postgres

  catalog-api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build: 
      context: .
      dockerfile: BooksShop.Catalog/BooksShop.Catalog.API/Dockerfile

volumes:
  postgres_data:
